// client/src/lib/components/ui/ButtonInput.svelte
<script lang="ts">
import { createEventDispatcher } from "svelte";

export let disabled: boolean = false;

const dispatch = createEventDispatcher();

const onClick = (e: Event) => {
    dispatch('click', e);
}
</script>

<button {disabled} on:click={onClick} style="border-color: { disabled ? 'gray' : 'black' }; cursor: { disabled ? 'auto' : 'grab' };"><slot></slot></button>

<style>
button {
    border: 4px solid gray;
    margin: 8px;
    background-color: transparent;
    font-size: 1.5vw;
}
</style>

// client/src/elements/ButtonInput.tsx
function ButtonInput({ disabled=false, text, onClick }: { disabled?: boolean, text: string, onClick: () => any }) {
    const style = {
        border: disabled ? '4px solid gray' : '4px solid black',
        margin: '8px',
        backgroundColor: 'transparent',
        cursor: disabled ? 'auto' : 'grab',
        fontSize: '1.5vw'
    }
    return <button style={style} onClick={onClick}>{text}</button>
}

export default ButtonInput;
