// client/src/layout/FullscreenBox.tsx
import { useEffect, useRef, useState } from "react";

function FullscreenBox({ children }: { children: React.ReactNode }) {
    const fullscreenElmnt = useRef<HTMLDivElement>(null);
    const [fullscreen, setFullscreen] = useState(false);
    const handleClick = async () => {
        if (document.fullscreenElement == fullscreenElmnt.current) {
            await document.exitFullscreen();
        } else {
            await fullscreenElmnt.current!.requestFullscreen();
        }
    }
    const style = {
        cursor: 'grab',
        height: fullscreen ? '100vh' : '30vw',
        width: 'auto'
    }

    useEffect(() => {
        if (fullscreenElmnt.current != null) {
            fullscreenElmnt.current.addEventListener('fullscreenchange', (event) => {
                setFullscreen(document.fullscreenElement == fullscreenElmnt.current);
            });
        }
    }, []);
    return <div style={style} ref={fullscreenElmnt} onClick={handleClick}>{children}</div>
}

export default FullscreenBox;

// client/src/lib/components/ui/FullscreenBox.svelte
<script lang="ts">
    let fullscreenDiv: HTMLDivElement;
    const toggleFullscreen = async () => {
        if (fullscreenDiv && document.fullscreenElement == fullscreenDiv) {
            await document.exitFullscreen();
        } else {
            await fullscreenDiv.requestFullscreen();
        }
    }
</script>

<div bind:this={fullscreenDiv} on:click={toggleFullscreen} class="centered"><slot></slot></div>

<style>
div {
    cursor: 'grab';
    height: 100%;
    width: auto;
}

.centered {
    display: flex;
    justify-content: center;
}
</style>
