// client/src/settings/schedule/Schedule.tsx
import { useEffect, useState } from "react";
import DayHour from "./DayHour";
import Row from "../../layout/Row";
import Center from "../../layout/Center";

const weekdayMap = ['月', '火', '水', '木', '金', '土', '日'];

function Schedule({ numDays, numHours }: { numDays: number, numHours: number}) {
    const [state, setState] = useState<Array<Array<boolean>>>(new Array(numDays).fill(new Array(numHours).fill(true)));

    const toggleAll = () => {
        let allEnabled = state.every(day => day.every(hr => hr));
        setState(state.map(d => d.map(() => !allEnabled)));
    }
    const toggleHour = (hr: number) => {
        let allEnabled = state.every(day => day[hr]);
        setState(state.map(d => d.map((h, indexHr) => indexHr == hr ? !allEnabled : h)));
    }
    const toggleDay = (day: number) => {
        let allEnabled = state[day].every(hr => hr);
        setState(state.map((d, indexDay) => indexDay == day ? d.fill(!allEnabled) : d));
    }
    const toggleDayHour = (day: number, hr: number) => {
        setState(state.map((d, indexDay) => d.map((h, indexHr) => indexHr == hr && indexDay == day ? !h : h)));
    }

    useEffect(() => {
        fetch('schedule', { method: 'POST', body: JSON.stringify(state), headers: { 'Content-Type': 'application/json' }});
    }, [state]);

    let allRows = [];
    let topRow = [<DayHour key={-1} enabled={state.every(day => day.every(hr => hr))} handleClick={toggleAll}> </DayHour>];
    for (let i = 0; i < numHours; i++) {
        topRow.push(<DayHour key={i} enabled={state.every(day => day[i])} handleClick={() => {toggleHour(i)}}>{i+1}</DayHour>);
    }
    allRows.push(<Row key={-1}>{topRow}</Row>);
    for (let day = 0; day < numDays; day++) {
        let curRow = [<DayHour key={-1} enabled={state[day].every(hr => hr)} handleClick={() => {toggleDay(day)}}>{weekdayMap[day] ?? day+1}</DayHour>];
        for (let hr = 0; hr < numHours; hr++) {
            curRow.push(<DayHour key={hr} enabled={state[day][hr]} handleClick={() => {toggleDayHour(day, hr)}} />);
        }
        allRows.push(<Row key={day}>{curRow}</Row>);
    }


    const style = {
        display: 'flex',
        flexDirection: 'column' as const,
        border: '1px solid white',
        width: 'min-content',
        userSelect: 'none' as const,
        backgroundColor: 'black',
        margin: 'auto'
    };
    return <Center><div style={style}>{allRows}</div></Center>;
}

export default Schedule;

// src/lib/components/schedule/Schedule.svelte
<script lang="ts">
    const days = ['月', '火', '水', '木', '金', '土', '日'];
    const numHours = 24;
    let state: Array<Array<boolean>> = new Array(7).fill(0).map(() => Array(24).fill(true));

    const toggleAll = () => {
        const allEnabled = state.every(day => day.every(h => h));
        for (const day of state) day.fill(!allEnabled);
        state = state;
        fetch('schedule', { method: 'POST', body: JSON.stringify(state) });
    }
    const toggleHour = (hr: number) => {
        const allEnabled = state.every(day => day[hr]);
        for (const day of state) day[hr] = !allEnabled;
        state = state;
        fetch('schedule', { method: 'POST', body: JSON.stringify(state) });
    }
    const toggleDay = (day: number) => {
        state[day].fill(!state[day].every(h => h));
        state = state;
        fetch('schedule', { method: 'POST', body: JSON.stringify(state) });
    }
    const toggleDayHour = (day: number, hr: number) => {
        state[day][hr] = !state[day][hr];
        fetch('schedule', { method: 'POST', body: JSON.stringify(state) });
    }
</script>

<div class="schedule">
    <div class="row">
        <button on:click={toggleAll} style="background-color: {state.every(arr=>arr.every(h=>h)) ? 'green' : 'black'}"></button>
        {#each { length: numHours } as _, hr (hr)}
            <button on:click={()=>toggleHour(hr)} style="background-color: {state.every(arr=>arr[hr]) ? 'green' : 'black'}">{hr+1}</button>
        {/each}
    </div>
    {#each days as day, i (i)}
        <div class="row">
            <button on:click={()=>toggleDay(i)} style="background-color: {state[i].every(h=>h) ? 'green' : 'black'}">{ day }</button>
            {#each {length: numHours} as _, hr (hr)}
                <button on:click={()=>toggleDayHour(i,hr)} style="background-color: {state[i][hr] ? 'green' : 'black'}"></button>
            {/each}
        </div>
    {/each}
</div>

<style>
.schedule {
    text-align: center;
    border: 1px solid white;
    width: min-content;
    height: min-content;
}
.row {
    display: flex;
    flex-direction: row;
}
button {
    margin: 0px;
    padding: 0px;
    width: 3vw;
    height: 3vw;
    border: 1px solid white;
    font-size: 2vw;
    color: white;
}
</style>
